apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.port }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.service.port }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}