apiVersion: v1
kind: PersistentVolume
metadata:
  name: sale-log-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/logs/sale"